excel: # metadata description of the excel file for mapping to the expected format
  fields:
    name: 'Nome'
    surname: 'Cognome'
    id: 'Matricola' 
  data_marker: # needed to skip header rows in ugly formatted excel lists (e.g., those resulting from the infamous esse3)
    skip_until: Elenco Studenti Iscritti all'Appello
    on_column: 0
  encoding: latin-1 # also this might infamously be needed by the silly esse3 output
exam: # exam details
  name: Fondamenti di Programmazione – Ing. Elettronica e Ing. Gestionale # exam name
  language: Italian # localization to be used
  shuffle_questions: yes # whether the questions are proposed in a random order or in the original one
  shuffle_answers: yes # whether the answers to each question are randomly rearranged
  grading_scale: Uniform # either Uniform, meaning 1/n for correct and wrong answers and 0 for unanswered or a triple of points for correct, wrong, unanswered
  page_limits: 4 # The LaTeX compilation fails and tries to create another exam if the page limit is exceeded
  max_questions: 20
questions: 
  - from: "01 notazione posizionale 01.md"
    draw: 1
  - from: "01 notazione posizionale 02.md"
    draw: 1
  - from: "01 notazione posizionale 03.md"
    draw: 1
  - from: "02 codifica interi 01.md"
    draw: 1
  - from: "02 codifica interi 02.md"
    draw: 1
  - from: "02 codifica interi 03.md"
    draw: 1
  - from: "03 codifica reali 01.md"
    draw: 1
  - from: "03 codifica reali 02.md"
    draw: 1
  - from: "04 operazioni in ca2 01.md"
    draw: 1
  - from: "04 operazioni in ca2 02.md"
    draw: 1
  - from: "05 codifica dei testi 01.md"
    draw: 1
  - from: "06 programmazione strutturata 01.md"
    draw: 1
  - from: "06 programmazione strutturata 02.md"
    draw: 1
  - from: "07 algoritmi 01.md"
    draw: 1
  - from: "07 algoritmi 02.md"
    draw: 1
header: |
  \sf
  \large \theexam \newline
  \normalsize \thedate – \thematriculationno, \thestudent \newline
  Durata 55 minuti - Pagina \thepage \newline
  \normalfont
preamble: | 
  \sf
  Matricola: \makebox[2cm]{\hrulefill} Nome e cognome: \hrulefill

  \begin{tcolorbox}[title={\sf \Warning~**Leggere con molta attenzione**~\Warning},colframe=black!10!white, center title,coltitle=black]
  \sf \footnotesize
  Il compito va **svolto su questo foglio** che dovrà essere consegnato al termine della prova. 
  Riportate **subito** il vostro **numero di matricola** e **nominativo** qui sopra.

  Le **risposte definitive** dovranno essere fornite **annerendo i cerchi presenti**
  sulla parte destra del foglio **come indicato nella prima figura**. Tutte le altre indicazioni
  sono scorrette.

  ![](images/omr_instructions.pdf)  

  \Warning~Poiché **NON È CONSENTITA LA CORREZIONE** delle risposte definitive si consiglia di appuntare le
  risposte sulla parte contenente il testo e di riportarle sulla parte a lettura ottica (con i cerchi) 
  *solamente* quando si è certi delle risposte stesse. 
  \Warning~**Non stropicciare il foglio e non scrivere o scarabocchiare sulla parte della pagina contenente i cerchi né sui QRCode**, 
  ciò potrebbe invalidare le vostre risposte e di conseguenza il compito. 
  Potete prendere appunti sulla parte contenente il testo delle domande, ma la risposta definitiva è 
  quella riportata sulla parte a lettura ottica.

  Si ricorda che **non è consentito comunicare** utilizzando qualunque mezzo, né condividere alcun materiale;
  ciò darà luogo **immediatamente** e **incontestabilmente** all'**annullamento** della prova d'esame.
  Alcune domande possono avere **una o più risposte corrette**: l'individuazione di **tutte** le risposte corrette 
  attribuirà **1 punto**.
  
  \normalfont \normalsize
  \end{tcolorbox}  
footer: # currently no footer
choices:
  circled: True
  oneparchoices: True
packages:
  tcolorbox: []