excel: # metadata description of the excel file for mapping to the expected format
  fields:
    name: 'Nome'
    surname: 'Cognome'
    id: 'Matricola' 
  data_marker: # needed to skip header rows in ugly formatted excel lists (e.g., those resulting from the infamous esse3)
    skip_until: Elenco Studenti Iscritti all'Appello
    on_column: 0
  encoding: latin-1 # also this might infamously be needed by the silly esse3 output
exam: # exam details
  name: Modulo di Informatica - CCLM Medicina e Chirurgia # exam name
  language: Italian # localization to be used
  shuffle_questions: yes # whether the questions are proposed in a random order or in the original one
  shuffle_answers: yes # whether the answers to each question are randomly rearranged
  grading_scale: Uniform # either Uniform, meaning 1/n for correct and wrong answers and 0 for unanswered or a triple of points for correct, wrong, unanswered
  page_limits: 4 # The LaTeX compilation fails and tries to create another exam if the page limit is exceeded
  max_questions: 11
questions: 
  - from: "*.md"
    draw: 2
  - from: "12-open.md"
    draw: 2
header: |
  \sf
  \Large \theexam \newline
  \normalsize \thedate \newline 
  MATRICOLA \fillin[][3cm] \newline
  NOME \fillin[][4cm] COGNOME \fillin[][4cm] \newline 
  Durata 1 ora
  \normalfont
preamble: | 
  \small \sf
  Il compito va **svolto su questo foglio** che dovrà essere consegnato al termine della prova. 
  Le **risposte definitive** dovranno essere fornite annerendo i cerchi presenti  sulla parte destra del foglio come indicato nella figura. 

  ![](images/omr_instructions.pdf)

  **Non è consentita la correzione** delle risposte definitive: si consiglia di ricopiare 
  le risposte sulla parte a lettura ottica *solamente* quando si è certi delle risposte stesse. 
  \normalsize 
  
footer: # currently no footer
choices:
  circled: True
  oneparchoices: True